### ISSUE TITLE
Footnote popups are hard to open on touch devices

### ISSUE THREAD

**Issue by wisp3rwind** [johnfactotum/foliate#1482]
**Is your feature request related to a problem? Please describe.**
I'm using Foliate on a 2-in-1 Laptop/Tablet device. When in tablet mode, I navigate Foliate by touch. That works great for many things, but one paper cut I encounter is with regards to selecting footnotes (such as the asterisk in the screenshot below): Opening the footnote popup requires hitting the footnote index quite precisely. That will usually take on the order of 5-10 attempts (and I might accidentally close the popup again when clicking to fast to realize that I succeeded).

![Image](https://github.com/user-attachments/assets/bf4478bd-17f4-4a25-9c48-57ca732bb2b2)

**Describe the solution you'd like**
Footnotes have larger click targets (at least for touch input). Usually, there's no other clickable content near-by that this could conflict with.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by johnfactotum** [comment]
I would suggest that you set a custom style (see https://github.com/johnfactotum/foliate/blob/gtk4/docs/faq.md#can-i-set-my-own-custom-css-styles) and add some padding to `a:any-link`, or even add an icon, etc., with pseudo-elements. It's also possible to target only the links that are note references with `a[epub|type~="noteref"], a[role~="doc-noteref"]` but it would only work for books that have set the correct semantic info.

**Comment by wisp3rwind** [comment]
So, I did this (with some LLM assistance, since I don't really know any CSS):

```css
a:any-link {
  padding-left: 7px;
  padding-right: 7px;
  padding-top: 5px;
  padding-bottom: 5px;
  background-color: rgba(200, 200, 250, 0.2); /* Light pastel background */
  border-radius: 4px;
  transition: background-color 0.1s ease, box-shadow 0.1s ease; /* Smooth hover effect */
}

a:any-link:hover,
a:any-link:focus {
  background-color: rgba(150, 150, 250, 0.3); /* Slightly darker on hover */
  box-shadow: 0 0 5px rgba(150, 150, 250, 0.5); /* Glow effect for focus */
}

a:any-link:active {
  background-color: rgba(100, 100, 250, 0.4); /* Even darker when pressed */
}
```

which seems to work quite nicely.

Sometimes, it still happens that I want to click a link, but also move the touch point horizontally a tiny bit, such that the gesture is interpreted as the beginning of a swipe to change the page (and the click won't be registered as such, even when eventually, no page change happens). That might be unavoidable, however. In any case, the behavior is much improved already.
