### ISSUE TITLE
Detect dark theme without JavaScript

### ISSUE THREAD

**Issue by daniel-j** [johnfactotum/foliate#178]
Is there a way to detect if a dark theme is active without using JavaScript and comparing text and body background color.
For example I do this to support Apple Books' themes:
```css
:root[__ibooks_internal_theme*="Gray"] .titleart img,
:root[__ibooks_internal_theme*="Night"] .titleart img {
	-webkit-filter: invert(1);
	filter: invert(1);
}
:root[__ibooks_internal_theme*="Gray"] .titleart img {
	opacity: 0.8;
}
:root[__ibooks_internal_theme*="Night"] .titleart img {
	opacity: 0.7;
}
```
The image is black with transparent background, and it is inverted for dark themes.
Foliate could add support by adding a CSS class to the html element of the ebook document if the background is darker than the text color. Alternatively, although I think it requires patches to Webkit2, would be to add support for the `prefers-color-scheme: dark` CSS media query.
